# Generated by Django 5.2.4 on 2025-07-10 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_rutina', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diarutina',
            options={'verbose_name': 'Día de Rutina', 'verbose_name_plural': 'Días de Rutina'},
        ),
        migrations.AlterModelOptions(
            name='ejercicio',
            options={'verbose_name': 'Ejercicio', 'verbose_name_plural': 'Ejercicios'},
        ),
        migrations.AlterModelOptions(
            name='ejerciciodia',
            options={'ordering': ['orden'], 'verbose_name': 'Ejercicio por Día', 'verbose_name_plural': 'Ejercicios por Día'},
        ),
        migrations.AlterModelOptions(
            name='progreso',
            options={'verbose_name': 'Progreso', 'verbose_name_plural': 'Progresos'},
        ),
        migrations.AlterModelOptions(
            name='rutina',
            options={'verbose_name': 'Rutina', 'verbose_name_plural': 'Rutinas'},
        ),
    ]
