# Generated by Django 5.2.4 on 2025-07-10 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categoria',
            field=models.CharField(choices=[('TEC', 'Tecnología'), ('VID', 'Vida'), ('ART', 'Arte'), ('OTR', 'Otra')], default='OTR', max_length=3),
        ),
    ]
